
from random import randint
print(randint(1, 6))  # e.g. 3

# import randint              # ModuleNotFoundError: ...
# from randint import random  # ModuleNotFoundError: ...
# import randint from random  # SyntaxError: ...
