
from math import sqrt as squareRoot
print(squareRoot(16))  # 4.0

# import math.sqrt as squareRoot       # ModuleNotFoundError: ...
# import sqrt from math as squareRoot  # SyntaxError: ...
# from math.sqrt as squareRoot         # SyntaxError: ...
