
import sys
print('Before the exit!')  # Before the exit!
sys.exit()
# sys.halt()      # AttributeError: ...
# sys.stop()      # AttributeError: ...
# sys.terminat()  # AttributeError: ...
print('After the exit!')
